apiVersion: v1
kind: Service
metadata:
  name: locust-server-service-connect
spec:
  ports:
    - port: 5557
      protocol: TCP
      targetPort: 5557
  clusterIP: 10.96.0.2
  selector:
    app: locust-server-pod
  type: LoadBalancer
