apiVersion: v1
kind: PersistentVolume
metadata:
  name: locust-report-pv
spec:
  storageClassName: manual
  capacity:
    storage: 64Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/reports"