apiVersion: v1
kind: Service
metadata:
  name: locust-server-service
spec:
  ports:
    - port: 5558
      name: loc-server-p2
      protocol: TCP
      targetPort: loc-server-p2
  selector:
    app: locust-server-pod
