apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
  name: locust-report-pvc
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany 
  resources:
    requests:
      storage: 32Mi